appName: dist_app
logLevel: INFO
CONFIG:
  cfg_file_path: "APP_ROOT_DIR/cfg"
  log_file_path: "APP_ROOT_DIR/log"
  out_file_path: "APP_ROOT_DIR/data"
  warehouse_path: "APP_ROOT_DIR/data/user/hive/warehouse"
  sql_file_path: "APP_ROOT_DIR/sql"
  source_file_path: "APP_ROOT_DIR/data"
  plot_path: "APP_ROOT_DIR/plot"
